version: "3.9"
services:
  vigor:
    container_name: vigor-auth
    ports:
      - "8080"
    environment:
      - iss=$iss
      - sub=$sub
      - exp=$exp
      - name=$name
      - mongodb_host=$mongodb_host
    volumes:
      - vigor_auth_keys:/keys
    build: .
    image: vigor-auth
    depends_on:
      - "mongodb"
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017"
    volumes:
      - dlxyz_db:/data/db
    restart: always
volumes:
  vigor_auth_keys:
  dlxyz_db:
