version: "3.9"
services:
  vigor:
    container_name: vigor-auth
    ports:
      - "8080"
    environment:
      - iss=$iss
      - sub=$sub
      - exp=$exp
      - name=$name
      - mongodb_host=$mongodb_host
    volumes:
      - vigor_auth_keys:/keys
    build: .
volumes:
  vigor_auth_keys:
